/*
 * TRANSITION_STATE.h
 *
 *  Created on: 12.01.2017
 *      Author: thoma
 */

#ifndef SRC_VEINS_MASTERTHESIS_WAVE_MESSAGE_TRANSITION_STATE_H_
#define SRC_VEINS_MASTERTHESIS_WAVE_MESSAGE_TRANSITION_STATE_H_


enum TRANSITION_STATE
{
   NEUTRAL, PARK, FORWARD_GEARS, REVERSE_GEARS, RESERVED1, RESERVED2, RESERVED3, UNAVAILABLE
};


#endif /* SRC_VEINS_MASTERTHESIS_WAVE_MESSAGE_TRANSITION_STATE_H_ */
