/*
 * BrakeSystemStatus.h
 *
 *  Created on: 12.01.2017
 *      Author: thoma
 */

#ifndef SRC_VEINS_MASTERTHESIS_WAVE_MESSAGE_HEADERS_BRAKESYSTEMSTATUS_H_
#define SRC_VEINS_MASTERTHESIS_WAVE_MESSAGE_HEADERS_BRAKESYSTEMSTATUS_H_

enum wheelBrakes {
    UNAVAILABLE_WHEELBRAKES, LEFTFRONT_WHEELBRAKES, LEFTREAR_WHEELBRAKES, RIGHTFRONT_WHEELBRAKES, RIGHTREAR_WHEELBRAKES,
};

enum traction {
    UNAVAILABLE_TRACTION, OFF_TRACTION, ON_TRACTION, ENGAGED_TRACTION
};

enum antiLockBrakeStatus {
    UNAVAILABLE_ABS, OFF_ABS, ON_ABS, ENGAGED_ABS
};
enum scs {
    UNAVAILABLE_SCS, OFF_SCS, ON_SCS, ENGAGED_SCS
};
enum brakeBoost {
    UNAVAILABLE_BRAKEBOOST, OFF_BRAKEBOOST, ON_BRAKEBOOST, ENGAGED_BRAKEBOOST
};
enum auxBrakes {
    UNAVAILABLE_AUXBRAKES, OFF_AUXBRAKES, ON_AUXBRAKES, ENGAGED_AUXBRAKES
};
struct BrakeSystemStatus {

    wheelBrakes WHEELBRAKES;
    traction TRACTION;
    antiLockBrakeStatus ABS;
    scs SCS;
    brakeBoost BRAKEBOOST;
    auxBrakes AUXBRAKES;

};

#endif /* SRC_VEINS_MASTERTHESIS_WAVE_MESSAGE_HEADERS_BRAKESYSTEMSTATUS_H_ */
